plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'io.freefair.lombok' version '8.10'
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

base {
	archivesName = project.archives_base_name
}
version = "${project.minecraft_version}-${project.mod_version}"
group = project.maven_group

Properties additionalProperties = new Properties()
if (file("extra.properties").exists()) {
	additionalProperties.load(file("extra.properties").newReader())
}

repositories {
	mavenCentral()
	maven { url 'https://masa.dy.fi/maven' }
	maven { url 'https://jitpack.io' }
	maven { url 'https://maven.fallenbreath.me/releases' }
}

dependencies {
	compileOnly("org.projectlombok:lombok:1.18.46")
	annotationProcessor("org.projectlombok:lombok:1.18.46")

	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation "com.github.sakura-ryoko:malilib:${project.malilib_version}"
	// Download AdvancedChatCore-26.2-2.4.jar from:
	// https://github.com/ThePro1604/AdvancedChatCore-Update/releases/download/v26.2-2.4/AdvancedChatCore-26.2-2.4.jar
	// and place it in the libs/ directory
	implementation files('../AdvancedChatCore-Update/build/libs/AdvancedChatCore-26.2-2.4.jar')
	implementation 'com.github.DarkKronicle.Konstruct:core:2.0.3-build1'
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 25
}

tasks.register('sourcesJar', Jar) {
	dependsOn classes
	archiveClassifier.set('sources')
	from sourceSets.main.allSource
}

jar {
	from "LICENSE.txt"
}
