org.gradle.jvmargs=-Xmx2G

# https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.18.6
loom_version=1.15.5
fabric_api_version=0.150.0+26.1.2

mod_version=2.3
maven_group=com.arematics
archives_base_name=AdvancedChatHUD

# https://jitpack.io/#sakura-ryoko/malilib
malilib_version=26.1.2-0.28.3
advancedchat_version=2.3

modrinth_slug=advancedchathud-next
modrinth_id=Lb4UH0ra

# default_release_type can be stable, beta, or alpha
default_release_type=stable
project_name=AdvancedChatHUD
project_url=https://modrinth.com/mod/advancedchathud-next
project_logo=https://raw.githubusercontent.com/Prospector/images/master/modmenu-logo.png
project_color=0x134bff
changelog_hide_unimportant_commits=true
changelog_max_commit_search=200
discord_webhook_changelog_line_limit=10